package shared

const (
	ERR_CANNOT_FETCH_EVENTS = iota
	ERR_EVENT_PARAMS_NOT_VALID
	ERR_UNABLE_TO_INSERT_EVENT
	ERR_JOIN_PARAMS_NOT_VALID
	ERR_QUERY_PARAM_NOT_FOUND
	ERR_UNABLE_TO_FETCH_EVENT
	ERR_EVENT_NOT_FOUND
)
